trigger:
  - main
  
resources:
  containers:
    - container: azurite
      image: mcr.microsoft.com/azure-storage/azurite
      networks: 
      - testes
      ports:
        - 10001:10001
        - 10002:10002
        - 10003:10003
    - container: mongodb
      image: mongo:latest
      networks: 
      - testes
      env:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: MongoDB2021!
      ports:
        - 27017:27017

variables:
  buildConfiguration: 'Release'
  vmImageName: 'ubuntu-latest'
  artifactFunctionApp: 'functionAppProcessarAcoes'
  functionAppProject: '**/FunctionAppProcessarAcoes.csproj'
  pathFunctionApp: './FunctionAppProcessarAcoes'
  fileLogExecutionFunctionApp: 'log-execucao-functionapp.log'
  testProject: '**/FunctionAppProcessarAcoes.IntegrationTests.csproj'
  AzureWebJobsStorage: 'UseDevelopmentStorage=true'
  IntervaloProcessamento: 6000
  MongoDB_Connection: 'mongodb://root:MongoDB2021!@localhost:27017'
  MongoDB_Database: 'DBAcoesTestesIntegrados'
  MongoDB_Collection: 'HistoricoAcoes'
  QueueName: 'queue-acoes'

stages:
- stage: Tests
  displayName: Testes da Function App
  jobs:
  - job: Tests
    displayName: Testes da Function App em .NET
    pool:
      vmImage: $(vmImageName)
    services:
      azurite: azurite
      mongodb: mongodb
    steps:
    - script: docker container ls
      displayName: Exibir containers em execução
    - task: UseDotNet@2
      displayName: Instalação do .NET 6
      inputs:
        packageType: 'sdk'
        version: '6.0.100'
    - script: |
        npm i azure-functions-core-tools@4
        npx func
      displayName: Instalar Azure Functions Core Tools v4
    - script: |
        cd $(pathFunctionApp)
        dotnet build --configuration Debug
        nohup npx func start > $(fileLogExecutionFunctionApp) 2>&1 &
        echo 'Aguardando a inicialização da Function App...'
        sleep 25s
      displayName: Executar a Function App
      env:
        AzureWebJobsStorage: $(AzureWebJobsStorage)
        MongoDB_Connection: $(MongoDB_Connection)
        MongoDB_Database: $(MongoDB_Database)
        MongoDB_Collection: $(MongoDB_Collection)
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '$(testProject)'
      displayName: Executar testes da Function App
    - script: |
        cd $(pathFunctionApp)
        cat $(fileLogExecutionFunctionApp)
      condition: Always()
      displayName: Exibir log de execução da Function App

- stage: Build
  displayName: Build da Function App
  dependsOn: Tests
  jobs:
  - job: Build
    displayName: Build da Function App em .NET
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: UseDotNet@2
      displayName: Instalação do .NET 6
      inputs:
        packageType: 'sdk'
        version: '6.0.100'
    - task: DotNetCoreCLI@2
      displayName: Build + Publish gerando Artifact
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(functionAppProject)'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    - task: PublishPipelineArtifact@1
      displayName: Publish do Artifact
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: $(artifactFunctionApp)

- stage: Deployment
  displayName: Deployment da Function App em Windows
  dependsOn: Build
  jobs:
  - job: Deployment
    displayName: Deployment da Function App no Azure
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: DownloadPipelineArtifact@2
      displayName: Download do Artifact gerado no stage de Build
      inputs:
        buildType: 'current'
        artifactName: $(artifactFunctionApp)
        targetPath: '$(System.DefaultWorkingDirectory)/publish'
    - task: AzureFunctionApp@1
      displayName: Deployment da Function App no Azure em Windows
      inputs:
        azureSubscription: 'AZURE SUBSCRIPTION'
        appType: 'functionApp'
        appName: 'groffeacoes'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        appSettings: '-FUNCTIONS_WORKER_RUNTIME "dotnet-isolated"'
        deploymentMethod: 'auto'